Repository py-why/dowhy, pull requests merged in 2022-10, with the labels that each got.

#609 Add E-Value Sensitivity Analysis Method
  docs/source/example_notebooks/sensitivity_analysis_testing.ipynb
  dowhy/causal_refuters/add_unobserved_common_cause.py
  dowhy/causal_refuters/evalue_sensitivity_analyzer.py
  tests/causal_refuters/test_add_unobserved_common_cause.py
Labels: review required

#698 Fix syntax error in dowhy_ranking_methods notebook
  docs/source/example_notebooks/dowhy_ranking_methods.ipynb
Labels: bug, maintenance

#693 Functional api/estimate effect function
  docs/source/example_notebooks/dowhy_functional_api.ipynb
  dowhy/causal_estimator.py
  dowhy/causal_model.py
Labels: enhancement

#700 Add workflow to mark and close stale issues
  .github/workflows/close-inactive-issues.yml
Labels: maintenance

#695 Change mechanics of Docker image build and usage
  .github/workflows/build-docker-image-docs.yml
  .github/workflows/docs.yml
  docs/Dockerfile
Labels: maintenance
